name: stan_workshop
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.3.5
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libgfortran5=11.2.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.1.2
  - requests=2.28.1
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=63.4.1
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.39.2
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - appnope==0.1.2
    - async-timeout==4.0.2
    - clikit==0.6.2
    - crashtest==0.3.1
    - frozenlist==1.3.1
    - httpstan==4.8.2
    - libgfortran==5.0.0
    - marshmallow==3.18.0
    - multidict==6.0.2
    - pastel==0.2.1
    - pylev==1.4.0
    - pysimdjson==3.2.0
    - pystan==3.5.0
    - webargs==8.2.0
    - yarl==1.8.1